### ISSUE TITLE
latent isn't 18x512 (it's 1x512)

### ISSUE THREAD

**Issue by aomv** [EvgenyKashin/stylegan2-distillation#17]
Hi!

 I used the command on the Readme file to generate random images and saved the latent

`python run_generator.py generate-images-custom --network=gdrive:networks/stylegan2-ffhq-config-f.pk
 --truncation-psi=0.7 --num 5000 --result-dir /mnt/generated_faces`
 
 Now I want to learn directions but the notebook that you recommend uses 18*512 for the latents while your repo generates 1x512 dimensional latents (https://github.com/Puzer/stylegan-encoder/blob/master/Learn_direction_in_latent_space.ipynb)

 How do I go about converting these 1x512 to 18x512 latents so I can train and apply the learned directions?

thank you

**Comment by EvgenyKashin** [comment]
Hi,

By default using a 1x512 or 18x512 doesn't make any difference, because the 18x512 is just 18 copies of the same 512 vector. But it's possible to search direction not in 512 W space, but in 18*512 W+ space. You could check it in our [notebook](https://github.com/EvgenyKashin/stylegan2-distillation/blob/master/stylegan2/Learn_direction_in_latent_space.ipynb) 

```
clf = LogisticRegression(class_weight='balanced')
# clf.fit(X_data.reshape((-1, 18*512)), y_data)  # this version for W+ 
clf.fit(X_data, y_data)  # default W version 
```

After you get the 512 vector you could make 18*512 from it:
`direction = np.tile(clf.coef_, (18, 1))`
